development:
  adapter: postgresql
  encoding: utf8
  database: reports_system_development
  pool: 5
  username: benanderson
  password:
  host: localhost

test: &test
  adapter: postgresql
  encoding: utf8
  database: reports_system_test
  username: benanderson

production:
  adapter: postgresql
  encoding: utf8
  database: reports_system_production
  pool: 5
  username: benanderson
  password:
  host: localhost